compile_pdf:
  image: tianon/latex
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    {%- if cookiecutter.type == "tex" -%}
    - latexmk -pdf {{cookiecutter.directory_name}}.tex

    {%- elif cookiecutter.type == "md" -%}
    - pandoc -t beamer --template=presentation.beamer {{cookiecutter.file_name}}.md -o {{cookiecutter.file_name}}.pdf

    {%- endif -%}
  artifacts:
    paths:
      - {{cookiecutter.file_name}}.pdf

